### ISSUE TITLE
Imagens excessivamente pesadas

### ISSUE THREAD

**Issue by enricodias** [wagstalos/projeto-investimentos#3]
Algumas imagens como `acoes.svg` são excessivamente pesadas, especialmente para quem acessa usando internet móvel. Existe alguma razão para elas serem assim? Se não existir, posso enviar uma PR com imagens reduzidas.

**Comment by wagstalos** [comment]
Realmente estão pesadas não existe razão, apenas nas animações que foram criadas no svg, pode alterar sim muito obrigado.
